In [88]:
# Imports

import zipfile
import pandas as pd

In [89]:
# --- One script: load data

import zipfile
import pandas as pd
from pathlib import Path


# 1) Config: ZIP file paths

zip_paths_Hip_Replacements_CCG = [
    r"..\..\data\external\data-pack-2016-17\Hip Replacement CCG 1617.csv.zip",
    r"..\..\data\external\data-pack-2017-18\Hip Replacements CCG 1718.csv.zip",
    r"..\..\data\external\data-pack-2018-19\Hip Replacement CCG 1819.csv.zip",
]

zip_paths_Hip_Replacements_Provider = [
    r"..\..\data\external\data-pack-2016-17\Hip Replacement Provider 1617.csv.zip",
    r"..\..\data\external\data-pack-2017-18\Hip Replacements Provider 1718.csv.zip",
    r"..\..\data\external\data-pack-2018-19\Hip Replacement Provider 1819.csv.zip",
]

zip_paths_Knee_Replacements_CCG = [
    r"..\..\data\external\data-pack-2016-17\Knee Replacement CCG 1617.csv.zip",
    r"..\..\data\external\data-pack-2017-18\Knee Replacements CCG 1718.csv.zip",
    r"..\..\data\external\data-pack-2018-19\Knee Replacement CCG 1819.csv.zip",
]

zip_paths_Knee_Replacements_Provider = [
    r"..\..\data\external\data-pack-2016-17\Knee Replacement Provider 1617.csv.zip",
    r"..\..\data\external\data-pack-2017-18\Knee Replacements Provider 1718.csv.zip",
    r"..\..\data\external\data-pack-2018-19\Knee Replacement Provider 1819.csv.zip",
]

zip_paths_key_facts = [
    r"..\..\data\external\data-pack-2016-17\Key Facts Hip and Knee Replacement 1617.csv.zip",
    r"..\..\data\external\data-pack-2017-18\Key Facts Hip and Knee Replacements 1718.csv.zip",
    r"..\..\data\external\data-pack-2018-19\Key Facts Hip and Knee Replacements 1819.csv.zip",
]

zip_paths_PartLink = [
    r"..\..\data\external\data-pack-2016-17\PartLink Hip and Knee Replacement 1617.csv.zip",
    r"..\..\data\external\data-pack-2017-18\PartLink Hip and Knee Replacements 1718.csv.zip",
    r"..\..\data\external\data-pack-2018-19\PartLink Hip and Knee Replacement 1819.csv.zip",
]

zip_paths_Equality = [
    r"..\..\data\external\data-pack-2016-17\Equality Hip and Knee Replacement 1617.csv.zip",
    r"..\..\data\external\data-pack-2017-18\Equality 1718.csv.zip",
    r"..\..\data\external\data-pack-2018-19\Equality 1819.csv.zip",
]

zip_paths_ProvComm_Hip_Knee = [
    r"..\..\data\external\data-pack-2016-17\ProvComm Hip and Knee Replacement 1617.csv.zip",
    r"..\..\data\external\data-pack-2017-18\ProvComm Hip and Knee Replacements 1718.csv.zip",
    r"..\..\data\external\data-pack-2018-19\ProvComm Hip and Knee Replacement 1819.csv.zip",
]

zip_paths_Time_Series = [
    r"..\..\data\external\data-pack-2016-17\Time Series Hip and Knee Replacement 1617.csv.zip",
    r"..\..\data\external\data-pack-2017-18\Time Series 1718.csv.zip",
    r"..\..\data\external\data-pack-2018-19\Time Series Hip and Knee Replacement 1819.csv.zip",
]

In [90]:
# 2) Read a CSV inside a ZIP (generic)

def read_csv_from_zip(zip_path, *, usecols=None, dtype=None):
    zip_path = Path(zip_path)

    with zipfile.ZipFile(zip_path, "r") as z:
        csv_name = next(
            name for name in z.namelist()
            if name.lower().endswith(".csv")
            and not name.startswith("__MACOSX/")
            and not Path(name).name.startswith("._")
        )

        with z.open(csv_name) as f:
            return pd.read_csv(
                f,
                usecols=usecols,
                dtype=dtype,
                low_memory=False
            )

In [91]:

# 3) Load & concat a list of ZIP->CSV files

def load_zip_csvs(zip_paths, *, usecols=None, dtype=None):
    return pd.concat(
        (read_csv_from_zip(p, usecols=usecols, dtype=dtype) for p in zip_paths),
        ignore_index=True,
        copy=False
    )

In [92]:
# 4) Build tables

df_Tbl_ProvComm_Hip_Knee            = load_zip_csvs(zip_paths_ProvComm_Hip_Knee)
df_Tbl_Time_Series                  = load_zip_csvs(zip_paths_Time_Series)
df_Tbl_Hip_Replacement_Provider     = load_zip_csvs(zip_paths_Hip_Replacements_Provider)
df_Tbl_Hip_Replacement_CCG          = load_zip_csvs(zip_paths_Hip_Replacements_CCG)
df_Tbl_Knee_Replacement_Provider    = load_zip_csvs(zip_paths_Knee_Replacements_Provider)
df_Tbl_Knee_Replacement_CCG         = load_zip_csvs(zip_paths_Knee_Replacements_CCG)
df_Tbl_Key_Facts                    = load_zip_csvs(zip_paths_key_facts)
df_Tbl_Equality                     = load_zip_csvs(zip_paths_Equality)
df_Tbl_PartLink                     = load_zip_csvs(zip_paths_PartLink)

# 5) Quick sanity checks

print("ProvComm Hip & Knee shape:", df_Tbl_ProvComm_Hip_Knee.shape)
print("Time Series shape:", df_Tbl_Time_Series.shape)
print("Hip replacement provider shape:", df_Tbl_Hip_Replacement_Provider.shape)
print("Hip replacement CCG shape:", df_Tbl_Hip_Replacement_CCG.shape)
print("Knee replacement provider shape:", df_Tbl_Knee_Replacement_Provider.shape)
print("Knee replacement CCG shape:", df_Tbl_Knee_Replacement_CCG.shape)
print("Key facts shape:", df_Tbl_Key_Facts.shape)
print("Equality shape:", df_Tbl_Equality.shape)
print("PartLink shape:", df_Tbl_PartLink.shape)

ProvComm Hip & Knee shape: (24099, 15)
Time Series shape: (13599, 28)
Hip replacement provider shape: (124844, 81)
Hip replacement CCG shape: (122294, 81)
Knee replacement provider shape: (139236, 81)
Knee replacement CCG shape: (136390, 81)
Key facts shape: (24187, 13)
Equality shape: (2196, 26)
PartLink shape: (943, 65)

In [93]:
def show_unique_values_knee_provider(df, max_values = 139236):
    for col in df.columns:
        uniques = df[col].dropna().unique()
        print(f"\nColumn: {col}")
        print(f"Unique count {len(uniques)}")
        print(f"Values (up to {max_values}): {uniques[:max_values]}") 

show_unique_values_knee_provider(df_Tbl_Knee_Replacement_Provider)

Column: Provider Code
Unique count 294
Values (up to 139236): ['ADP02' 'AHH' 'NN401' 'NN801' 'NT202' 'NT204' 'NT205' 'NT206' 'NT209'
 'NT210' 'NT212' 'NT213' 'NT214' 'NT215' 'NT218' 'NT219' 'NT224' 'NT225'
 'NT226' 'NT229' 'NT230' 'NT233' 'NT235' 'NT237' 'NT238' 'NT239' 'NT241'
 'NT242' 'NT244' 'NT245' 'NT301' 'NT302' 'NT304' 'NT305' 'NT308' 'NT309'
 'NT312' 'NT313' 'NT314' 'NT315' 'NT316' 'NT317' 'NT318' 'NT319' 'NT320'
 'NT321' 'NT322' 'NT324' 'NT325' 'NT327' 'NT332' 'NT333' 'NT337' 'NT339'
 'NT343' 'NT344' 'NT345' 'NT347' 'NT348' 'NT350' 'NT351' 'NT364' 'NT401'
 'NT402' 'NT403' 'NT404' 'NT405' 'NT406' 'NT408' 'NT409' 'NT410' 'NT411'
 'NT412' 'NT413' 'NT414' 'NT416' 'NT417' 'NT418' 'NT419' 'NT420' 'NT421'
 'NT422' 'NT423' 'NT424' 'NT427' 'NT428' 'NT429' 'NT430' 'NT431' 'NT432'
 'NT433' 'NT434' 'NT435' 'NT436' 'NT437' 'NT438' 'NT439' 'NT440' 'NT441'
 'NT443' 'NT445' 'NT446' 'NT447' 'NT448' 'NT449' 'NT450' 'NT451' 'NT455'
 'NT457' 'NT497' 'NTE02' 'NTP11' 'NTP13' 'NTP15' 'NTPH1' 'NTPH2' 'NTPH5'
 'NTX11' 'NTX12' 'NV302' 'NV313' 'NV323' 'NVC01' 'NVC02' 'NVC04' 'NVC05'
 'NVC06' 'NVC07' 'NVC08' 'NVC09' 'NVC11' 'NVC12' 'NVC13' 'NVC14' 'NVC15'
 'NVC16' 'NVC17' 'NVC18' 'NVC19' 'NVC20' 'NVC21' 'NVC22' 'NVC23' 'NVC25'
 'NVC28' 'NVC40' 'NVG01' 'NWF01' 'NXM01' 'R1F' 'R1H' 'R1K' 'RA2' 'RA3'
 'RA4' 'RA9' 'RAE' 'RAJ' 'RAL' 'RAN' 'RAP' 'RAS' 'RBA' 'RBD' 'RBK' 'RBL'
 'RBN' 'RBT' 'RBZ' 'RC1' 'RC9' 'RCB' 'RCD' 'RCF' 'RCX' 'RD1' 'RD8' 'RDD'
 'RDE' 'RDU' 'RDZ' 'RE9' 'REF' 'REM' 'RF4' 'RFF' 'RFR' 'RFS' 'RGN' 'RGP'
 'RGQ' 'RGR' 'RGT' 'RH8' 'RHM' 'RHQ' 'RHU' 'RHW' 'RJ1' 'RJ7' 'RJC' 'RJE'
 'RJF' 'RJL' 'RJN' 'RJR' 'RJZ' 'RK5' 'RK9' 'RKB' 'RKE' 'RL1' 'RL4' 'RLN'
 'RLQ' 'RLT' 'RM1' 'RM2' 'RM3' 'RMC' 'RN3' 'RN5' 'RN7' 'RNA' 'RNL' 'RNQ'
 'RNS' 'RNZ' 'RP5' 'RPA' 'RQ6' 'RQ8' 'RQM' 'RQQ' 'RQW' 'RQX' 'RR1' 'RR7'
 'RR8' 'RRF' 'RRJ' 'RRV' 'RTD' 'RTE' 'RTF' 'RTG' 'RTH' 'RTK' 'RTP' 'RTR'
 'RTX' 'RVJ' 'RVR' 'RVV' 'RVW' 'RVY' 'RW3' 'RW6' 'RWA' 'RWD' 'RWE' 'RWF'
 'RWG' 'RWH' 'RWJ' 'RWP' 'RWW' 'RWY' 'RX1' 'RXC' 'RXF' 'RXH' 'RXK' 'RXL'
 'RXN' 'RXP' 'RXQ' 'RXR' 'RXW' 'RYJ' 'RYR' 'RJ2' 'RMP' 'NQM01' 'NT211'
 'NXM04' 'R0A' 'AVQ' 'NFH01' 'NT30A' 'NT310' 'NVC0R' 'NYW01' 'RRK']

Column: Procedure
Unique count 1
Values (up to 139236): ['Knee Replacement']

Column: Revision Flag
Unique count 2
Values (up to 139236): [0 1]

Column: Year
Unique count 3
Values (up to 139236): ['2016/17' '2017/18' '2018/19']

Column: Age Band
Unique count 7
Values (up to 139236): ['*' '50 to 59' '60 to 69' '70 to 79' '80 to 89' '90 to 120' '40 to 49']

Column: Gender
Unique count 3
Values (up to 139236): ['*' '1' '2']

Column: Pre-Op Q Assisted
Unique count 3
Values (up to 139236): [2 1 9]

Column: Pre-Op Q Assisted By
Unique count 1
Values (up to 139236): [0]

Column: Pre-Op Q Symptom Period
Unique count 5
Values (up to 139236): [4 1 2 3 9]

Column: Pre-Op Q Previous Surgery
Unique count 3
Values (up to 139236): [2 1 9]

Column: Pre-Op Q Living Arrangements
Unique count 5
Values (up to 139236): [2 1 9 4 3]

Column: Pre-Op Q Disability
Unique count 3
Values (up to 139236): [1 2 9]

Column: Heart Disease
Unique count 2
Values (up to 139236): [9 1]

Column: High Bp
Unique count 2
Values (up to 139236): [9 1]

Column: Stroke
Unique count 2
Values (up to 139236): [9 1]

Column: Circulation
Unique count 2
Values (up to 139236): [9 1]

Column: Lung Disease
Unique count 2
Values (up to 139236): [9 1]

Column: Diabetes
Unique count 2
Values (up to 139236): [9 1]

Column: Kidney Disease
Unique count 2
Values (up to 139236): [9 1]

Column: Nervous System
Unique count 2
Values (up to 139236): [9 1]

Column: Liver Disease
Unique count 2
Values (up to 139236): [9 1]

Column: Cancer
Unique count 2
Values (up to 139236): [9 1]

Column: Depression
Unique count 2
Values (up to 139236): [1 9]

Column: Arthritis
Unique count 2
Values (up to 139236): [9 1]

Column: Pre-Op Q Mobility
Unique count 4
Values (up to 139236): [2 9 1 3]

Column: Pre-Op Q Self-Care
Unique count 4
Values (up to 139236): [2 1 9 3]

Column: Pre-Op Q Activity
Unique count 4
Values (up to 139236): [2 3 1 9]

Column: Pre-Op Q Discomfort
Unique count 4
Values (up to 139236): [3 2 9 1]

Column: Pre-Op Q Anxiety
Unique count 4
Values (up to 139236): [2 1 9 3]

Column: Pre-Op Q EQ5D Index Profile
Unique count 419
Values (up to 139236): [22232 22322 21331 21221 21121 99999 21332 21232 11321 22231 21231 21222
 11221 22223 22222 11322 22221 11122 22331 21233 21223 11211 21291 22233
 21321 11111 21322 11232 21132 11121 22291 11231 21191 29221 22323 22332
 21122 22333 22991 21131 11222 32333 11123 11113 21211 22321 21292 21323
 21229 29121 91191 21192 21333 11229 21129 32321 23221 21931 29332 11132
 11112 22239 21111 33332 39999 91121 23222 11192 29339 91221 33333 11131
 99222 12231 11291 29939 31331 22122 11331 19999 29291 22229 11129 22391
 29223 22931 23122 11133 22339 21339 23332 29231 23331 32332 12331 21112
 21999 21299 29331 92331 22132 21239 21391 92332 23231 33322 21133 12132
 23333 21123 22212 22293 11233 29222 21212 12221 12232 31332 22292 92239
 21293 33331 21939 22121 91931 22932 12222 21921 11212 91229 21932 11223
 23322 29232 11332 31339 23232 21312 12121 29122 22299 13232 12332 39933
 99329 29999 22392 11939 22131 99992 11911 29229 11191 21329 21311 29129
 22129 21199 21922 23321 22929 23121 29299 29321 22922 19199 12122 22329
 12131 21991 93321 21392 21929 29292 22921 11921 29399 12211 91132 91222
 91991 13221 19121 92221 32331 29131 11213 22211 12321 23391 99211 23233
 22311 21139 29239 93232 19131 91122 31232 12311 11311 32932 11329 23392
 39332 33232 31321 31999 91231 99929 99221 39211 11932 23329 29929 22923
 99332 23339 22999 21992 12322 93333 22111 22399 29211 21399 33321 92233
 31233 11239 92222 32391 92999 22939 99239 33233 91921 12223 23311 29921
 91233 91232 29111 32322 29932 21213 32232 23223 12333 92333 92932 19213
 23229 91339 91322 29333 13231 12139 32233 23932 12212 23921 99991 91321
 32221 91999 13131 21119 39993 31121 29233 29922 22133 23323 22192 31222
 91223 23211 92933 11292 91332 22312 31333 32291 22993 92231 33323 11119
 21113 19221 91291 11339 21933 22112 32231 23131 91211 93331 91311 31231
 29933 92992 92232 22123 22992 91131 93399 22139 12932 22933 12339 23292
 22213 11931 13331 39311 11293 13322 91129 13121 22191 91929 29931 31221
 99231 22393 32311 32312 23239 91333 11199 29992 32339 93332 99939 11922
 11219 23319 12233 12391 31329 99391 11139 91331 19211 92339 13339 92392
 92322 99121 99399 33339 99921 29112 13229 29322 93311 12193 31111 29323
 33231 12111 29991 22313 99122 23132 29212 19299 92922 33933 19931 11991
 19322 31239 91239 23313 11323 92321 29393 11992 11999 23293 11391 29392
 23212 11333 19911 92291 91922 31223 12291 29919 23291 21923 19933 31911
 19132 11193 22219 11299 32222 99299 99333 23393 99131 23299 99229 29911
 29293 12292 13222 29329 23931 93221 19919 93132 39333 21393 31133]

Column: Pre-Op Q EQ5D Index
Unique count 153
Values (up to 139236): [-0.016  0.189  0.101  0.691  0.727  0.03   0.088  0.433  0.055  0.159
  0.62   0.76   0.082  0.516  0.362  0.587  0.725 -0.003 -0.077  0.186
  0.883 -0.181  0.364  1.     0.293  0.157  0.124  0.796  0.228  0.024
 -0.074  0.656 -0.239  0.195  0.689 -0.484  0.291  0.414  0.814  0.26
  0.128 -0.135  0.015  0.208  0.193  0.848  0.85  -0.429  0.137 -0.594
  0.264 -0.144  0.552  0.17   0.173  0.028 -0.184 -0.113 -0.319  0.066
  0.779  0.02  -0.055 -0.166 -0.041  0.089 -0.349  0.222  0.639 -0.008
  0.743  0.053 -0.215 -0.358  0.623  0.585  0.812  0.255  0.079  0.099
 -0.126  0.416  0.692 -0.057 -0.005  0.091  0.487  0.15   0.244  0.621
  0.16   0.277 -0.248  0.378  0.71   0.329 -0.291  0.383 -0.157  0.452
  0.556 -0.371  0.119  0.258  0.746 -0.095 -0.322 -0.536  0.151  0.273
 -0.056  0.309 -0.261 -0.028 -0.17   0.014 -0.426  0.708  0.073  0.05
  0.213 -0.145 -0.086  0.106  0.331  0.312 -0.38  -0.331  0.345  0.675
 -0.19  -0.019  0.118  0.205 -0.044  0.148  0.313  0.177  0.138  0.067
 -0.112  0.336 -0.3    0.815  0.147 -0.09   0.037  0.197 -0.066 -0.059
  0.002  0.206 -0.286]

Column: Post-Op Q Assisted
Unique count 3
Values (up to 139236): [2 1 9]

Column: Post-Op Q Assisted By
Unique count 7
Values (up to 139236): [9 2 6 1 4 3 5]

Column: Post-Op Q Living Arrangements
Unique count 5
Values (up to 139236): [2 1 4 9 3]

Column: Post-Op Q Disability
Unique count 3
Values (up to 139236): [1 2 9]

Column: Post-Op Q Mobility
Unique count 4
Values (up to 139236): [2 1 9 3]

Column: Post-Op Q Self-Care
Unique count 4
Values (up to 139236): [9 1 2 3]

Column: Post-Op Q Activity
Unique count 4
Values (up to 139236): [2 1 9 3]

Column: Post-Op Q Discomfort
Unique count 4
Values (up to 139236): [2 1 9 3]

Column: Post-Op Q Anxiety
Unique count 4
Values (up to 139236): [3 2 1 9]

Column: Post-Op Q Satisfaction
Unique count 6
Values (up to 139236): [2 3 1 4 5 9]

Column: Post-Op Q Sucess
Unique count 6
Values (up to 139236): [1 2 3 5 4 9]

Column: Post-Op Q Allergy
Unique count 3
Values (up to 139236): [2 1 9]

Column: Post-Op Q Bleeding
Unique count 3
Values (up to 139236): [2 9 1]

Column: Post-Op Q Wound
Unique count 3
Values (up to 139236): [2 1 9]

Column: Post-Op Q Urine
Unique count 3
Values (up to 139236): [2 1 9]

Column: Post-Op Q Further Surgery
Unique count 3
Values (up to 139236): [2 1 9]

Column: Post-Op Q Readmitted
Unique count 3
Values (up to 139236): [2 1 9]

Column: Post-Op Q EQ5D Index Profile
Unique count 503
Values (up to 139236): [29223 11222 11111 11121 21221 99999 11211 21121 11221 11311 22322 11112
 91121 22222 21211 22221 21232 22223 21333 22232 23221 11922 11191 21223
 22332 21321 22191 21222 11219 22231 21332 21231 21212 12221 11123 21322
 22323 22211 11113 11212 91223 21233 11122 29221 12211 21122 22233 11223
 21213 21191 11911 12121 22321 22333 21111 11229 22292 12222 22121 11321
 12231 22392 91222 12111 29112 23222 22212 91919 22331 33331 22229 11193
 22922 11921 23322 29393 11119 21323 11929 92321 11131 29121 11192 91212
 11132 11199 32322 22239 11129 21112 23922 19323 21331 11233 11991 33333
 29213 91221 21291 91999 21292 21123 22932 32332 22111 11999 23323 22122
 22339 23333 91929 12112 33332 13221 29222 92221 12223 12219 23929 11291
 22291 11912 23232 99991 23321 11322 22293 93333 21229 21922 23311 22113
 91111 93399 21129 32333 12212 13311 33322 33321 22933 21911 21133 22131
 21131 22213 29292 19221 12321 99919 29229 12233 22992 11213 22299 29919
 21132 12122 29999 23921 11299 91211 19991 23332 11331 19129 11231 21921
 11232 29291 91931 91112 21311 91992 22312 91191 92233 21912 22929 31221
 92333 92211 91991 21999 91122 29991 29929 91922 21931 21929 29321 11312
 99122 21392 22391 19191 21119 91912 13333 29922 31311 99291 91911 91921
 13211 23213 19911 22119 91291 21312 91231 99911 19222 99922 99933 21391
 22112 32323 22311 11992 31321 11919 23331 21113 92332 19111 19211 19921
 12232 22129 32221 29333 31121 29332 12229 21932 29232 22329 92223 19121
 22393 32321 29231 33222 92229 22923 22939 92222 19992 33239 99231 21329
 91129 91332 13911 23231 22921 99111 12291 19999 19913 21991 21239 93312
 23211 23391 11332 92232 12311 22912 22911 21313 19112 33311 29921 13111
 23121 13121 23223 12322 22913 21319 23233 23111 19131 32331 29233 92932
 12129 23312 33312 13222 29322 12123 13321 22132 12399 22219 21192 32313
 92911 33392 22991 11139 91199 29212 33393 29311 99191 91299 92291 12131
 31332 92991 99299 12292 12323 91311 23339 92312 93393 31212 23393 11292
 33339 22399 99939 22319 39322 23239 91119 92331 13113 21299 99119 92111
 33913 32232 22123 12331 31111 99992 11133 99932 12911 29211 92212 21219
 23329 29113 19122 32222 91229 91232 93332 92992 93311 99229 33323 92311
 32311 99323 19229 31112 11313 29993 12213 99121 29992 21992 99292 31222
 39399 29199 19199 99222 12991 99221 29299 99199 12132 12293 99219 29392
 23131 21393 12332 11391 12312 99211 99112 29191 29911 33399 22999 19919
 91392 21339 99399 99993 99929 21199 91391 19213 22133 19929 12912 12239
 23939 92313 33313 99921 23933 22919 92392 23313 92999 92921 32231 99913
 31933 12333 21293 93322 22993 93121 93122 22313 92922 11333 92292 93933
 12191 91131 92322 33933 99331 29331 99393 31323 93313 13223 29239 92329
 19232 23292 32223 22192 92929 91192 29111 99129 31211 29933 33929 12921
 11319 23229 22931 11392 99321 91113 31911 31322 91399 23291 93392 99322
 32312 92231 32229 29339 23293 29931 13331 91123 23931 29932 99113 19329
 33921 12113 11323 19231 29122 29219 93232 93921 92931 12119 13119 21939
 31331 93999 21919 91213 92323 29139 93221 11293 29319 33119 19212]

Column: Post-Op Q EQ5D Index
Unique count 170
Values (up to 139236): [ 0.689  1.     0.796  0.691  0.883  0.727  0.76   0.556  0.189  0.848
  0.516  0.814  0.587  0.088  0.082 -0.135 -0.016  0.208  0.186 -0.074
  0.364  0.62   0.055  0.03   0.159  0.743  0.656  0.291  0.293  0.024
  0.71   0.414  0.812 -0.077  0.725  0.779 -0.181  0.255  0.309  0.692
  0.26  -0.239  0.85   0.585  0.623  0.433  0.124  0.815  0.137  0.639
 -0.003 -0.358  0.079  0.128  0.264  0.193 -0.056  0.101 -0.008 -0.594
  0.222 -0.319  0.746 -0.086  0.552 -0.349  0.744 -0.429  0.277  0.151
 -0.126  0.15   0.362  0.273  0.241 -0.484  0.708  0.342 -0.166 -0.095
 -0.041  0.091  0.195  0.205  0.329 -0.112  0.378  0.621 -0.184  0.17
  0.228  0.157  0.487  0.312  0.177  0.485 -0.28   0.242  0.4    0.095
  0.416  0.675 -0.221  0.383  0.119 -0.113  0.345  0.053  0.073  0.213
  0.015 -0.108 -0.055  0.331  0.099  0.452  0.251  0.028  0.436  0.244
  0.313 -0.028  0.258 -0.291  0.367 -0.248  0.202 -0.043  0.206  0.187
  0.219  0.02  -0.098  0.16  -0.215  0.093  0.229  0.2   -0.261  0.118
  0.066  0.336  0.002 -0.331  0.138  0.265  0.32   0.274  0.106  0.089
 -0.019 -0.005  0.381 -0.145 -0.208  0.037 -0.19  -0.17   0.147 -0.066
 -0.117  0.041 -0.163  0.3    0.048  0.067 -0.044  0.31   0.197 -0.144]

Column: Knee Replacement EQ 5D Index Post-Op Q Predicted
Unique count 123944
Values (up to 139236): [0.66985022 0.78574372 0.79147566 ... 0.86651283 0.87294702 0.87815547]

Column: Pre-Op Q EQ VAS
Unique count 102
Values (up to 139236): [ 63  30  65  90  95  75  89  85 999  39  60  35  80  88  83  70  82  50
  69  54 100  62  79  57  40  48  20  86  32  55  93  45  84  78  58  77
  73   0  74  47  36   5  49  67  25  92  72  98  97  66  99  12  10  42
  52  96  68  76  91  94  81  61  87  43  59  27  71  53  15  28  17   3
  37  46  24  44   6  38  26  16  64  41  34  51  33  29  22  31  56   2
  21  18  23   1  14   4   8  11   7   9  19  13]

Column: Post-Op Q EQ VAS
Unique count 102
Values (up to 139236): [ 50  58  80  90 999  85  60  95  65  40  70 100  68  23  75  97  81  88
  25  30  20  59  64  69  35  98  89  76  87  55  61  39  96  78  92  77
  67  84  73  91  79  82  34  74   0  45  71  10  86  49  93  99  94  29
  72  52  51  42  56  33  15  83  63  38  19  32  54  37  41  66   1  26
  53  57  21  48   7  44   5  22  46  47   9   3  36  62   4  28   2  18
  31  27  13  43  24   8  12  16  11  14  17   6]

Column: Knee Replacement EQ VAS_Post-Op Q Predicted
Unique count 119256
Values (up to 139236): [59.82426034 64.72978601 77.91970314 ... 69.25940382 78.73590704
 86.44769246]

Column: Knee Replacement Pre-Op Q Pain
Unique count 6
Values (up to 139236): [0 3 1 2 9 4]

Column: Knee Replacement Pre-Op Q Night Pain
Unique count 6
Values (up to 139236): [0 2 1 3 4 9]

Column: Knee Replacement Pre-Op Q Washing
Unique count 6
Values (up to 139236): [2 4 3 1 9 0]

Column: Knee Replacement Pre-Op Q Transport
Unique count 6
Values (up to 139236): [3 2 9 1 4 0]

Column: Knee Replacement Pre-Op Q Walking
Unique count 6
Values (up to 139236): [2 4 3 9 1 0]

Column: Knee Replacement Pre-Op Q Standing
Unique count 6
Values (up to 139236): [1 3 2 9 4 0]

Column: Knee Replacement Pre-Op Q Limping
Unique count 6
Values (up to 139236): [0 1 2 3 9 4]

Column: Knee Replacement Pre-Op Q Kneeling
Unique count 6
Values (up to 139236): [0 1 3 2 9 4]

Column: Knee Replacement Pre-Op Q Work
Unique count 6
Values (up to 139236): [1 2 3 9 0 4]

Column: Knee Replacement Pre-Op Q Confidence
Unique count 6
Values (up to 139236): [2 3 0 9 4 1]

Column: Knee Replacement Pre-Op Q Shopping
Unique count 6
Values (up to 139236): [2 3 9 0 1 4]

Column: Knee Replacement Pre-Op Q Stairs
Unique count 6
Values (up to 139236): [2 3 4 9 1 0]

Column: Knee Replacement Pre-Op Q Score
Unique count 49
Values (up to 139236): [15. 30. 24. 27. 32. 34. 23. 29. 19. 33. 13. 12.  4. 28. 22. 25. 31.  9.
 11. 21. 16. 14.  8.  6. 10. 18. 17. 26. 20. 39. 41. 40.  7.  5. 35. 36.
 37. 38.  3. 46.  1. 43. 42.  2. 44.  0. 45. 47. 48.]

Column: Knee Replacement Post-Op Q Pain
Unique count 6
Values (up to 139236): [3 4 1 2 0 9]

Column: Knee Replacement Post-Op Q Night Pain
Unique count 6
Values (up to 139236): [2 1 3 4 9 0]

Column: Knee Replacement Post-Op Q Washing
Unique count 6
Values (up to 139236): [3 4 2 1 9 0]

Column: Knee Replacement Post-Op Q Transport
Unique count 6
Values (up to 139236): [3 2 4 1 9 0]

Column: Knee Replacement Post-Op Q Walking
Unique count 6
Values (up to 139236): [2 4 3 1 9 0]

Column: Knee Replacement Post-Op Q Standing
Unique count 6
Values (up to 139236): [2 4 3 9 1 0]

Column: Knee Replacement Post-Op Q Limping
Unique count 6
Values (up to 139236): [3 4 2 0 9 1]

Column: Knee Replacement Post-Op Q Kneeling
Unique count 6
Values (up to 139236): [2 3 4 0 1 9]

Column: Knee Replacement Post-Op Q Work
Unique count 6
Values (up to 139236): [3 4 2 0 9 1]

Column: Knee Replacement Post-Op Q Confidence
Unique count 6
Values (up to 139236): [1 4 3 2 9 0]

Column: Knee Replacement Post-Op Q Shopping
Unique count 6
Values (up to 139236): [3 4 2 0 9 1]

Column: Knee Replacement Post-Op Q Stairs
Unique count 6
Values (up to 139236): [2 3 4 0 9 1]

Column: Knee Replacement Post-Op Q Score
Unique count 49
Values (up to 139236): [29. 39. 45. 43. 36. 46. 41. 25. 30. 37. 47. 48. 10. 42. 44. 33. 34. 23.
 32. 38. 16. 40. 22. 24. 27.  4. 20. 12. 31. 28. 21.  9. 26. 14. 35.  7.
 18. 17. 19. 11.  5. 13. 15.  6.  0.  3.  8.  2.  1.]

Column: Knee Replacement OKS Post-Op Q Predicted
Unique count 133527
Values (up to 139236): [28.123754   39.59274967 40.25078924 ... 35.84346766 37.13071274
 38.10165319]

In [94]:
columns_to_fix = ["Cancer", "Circulation", "Depression", "Diabetes", "Arthritis", "Heart Disease", "High Bp", "Kidney Disease", "Lung Disease", "Liver Disease", "Nervous System", "Stroke"]

df_Tbl_Knee_Replacement_Provider[columns_to_fix] = df_Tbl_Knee_Replacement_Provider[columns_to_fix].replace(9, 0)
df_Tbl_Knee_Replacement_Provider_cleaned = df_Tbl_Knee_Replacement_Provider.replace(9, pd.NA).replace("*", pd.NA)

Missing_Values = (pd.DataFrame({
    'Data_type':    df_Tbl_Knee_Replacement_Provider_cleaned.select_dtypes(include= "number").dtypes,
    'total':        df_Tbl_Knee_Replacement_Provider_cleaned.count(),
    'Missing':      df_Tbl_Knee_Replacement_Provider_cleaned.isna().sum()
})
.assign(
        complete_pct = lambda x: round(100 * ((x['total']) - x['Missing']) / (x['total']), 2)
)
.sort_values('complete_pct', ascending=False))
with pd.option_context(
    "display.max_rows", None, 
    "display.max_columns", None
):

    display(Missing_Values)

,Data_type,total,Missing,complete_pct
Arthritis,int64,139236,0,100.00
Diabetes,int64,139236,0,100.00
Cancer,int64,139236,0,100.00
Circulation,int64,139236,0,100.00
Depression,int64,139236,0,100.00
High Bp,int64,139236,0,100.00
Heart Disease,int64,139236,0,100.00
Kidney Disease,int64,139236,0,100.00
Pre-Op Q Assisted By,int64,139236,0,100.00
Post-Op Q EQ5D Index Profile,int64,139236,0,100.00
Procedure,NaN,139236,0,100.00
Revision Flag,int64,139236,0,100.00
Provider Code,NaN,139236,0,100.00
Year,NaN,139236,0,100.00
Liver Disease,int64,139236,0,100.00
Nervous System,int64,139236,0,100.00
Lung Disease,int64,139236,0,100.00
Stroke,int64,139236,0,100.00
Pre-Op Q EQ5D Index Profile,int64,139236,0,100.00
Post-Op Q EQ VAS,NaN,139211,25,99.98
Pre-Op Q EQ VAS,NaN,139211,25,99.98
Knee Replacement Pre-Op Q Washing,NaN,139111,125,99.91
Knee Replacement Pre-Op Q Pain,NaN,139038,198,99.86
Knee Replacement Post-Op Q Night Pain,NaN,138359,877,99.37
Knee Replacement Post-Op Q Confidence,NaN,138289,947,99.32
Knee Replacement Post-Op Q Stairs,NaN,138256,980,99.29
Knee Replacement Post-Op Q Work,NaN,138224,1012,99.27
Knee Replacement Post-Op Q Standing,NaN,138230,1006,99.27
Knee Replacement Post-Op Q Shopping,NaN,138231,1005,99.27
Pre-Op Q Previous Surgery,NaN,138194,1042,99.25
Knee Replacement Post-Op Q Limping,NaN,138139,1097,99.21
Knee Replacement Post-Op Q Kneeling,NaN,138145,1091,99.21
Pre-Op Q Symptom Period,NaN,138027,1209,99.12
Knee Replacement Post-Op Q Washing,NaN,137998,1238,99.10
Knee Replacement Post-Op Q Transport,NaN,137999,1237,99.10
Knee Replacement Post-Op Q Walking,NaN,137975,1261,99.09
Knee Replacement Post-Op Q Pain,NaN,137946,1290,99.06
Knee Replacement Pre-Op Q Night Pain,NaN,137932,1304,99.05
Knee Replacement Pre-Op Q Stairs,NaN,137898,1338,99.03
Knee Replacement Pre-Op Q Shopping,NaN,137893,1343,99.03
Knee Replacement Pre-Op Q Confidence,NaN,137894,1342,99.03
Knee Replacement Pre-Op Q Work,NaN,137880,1356,99.02
Knee Replacement Pre-Op Q Transport,NaN,137886,1350,99.02
Knee Replacement Pre-Op Q Kneeling,NaN,137840,1396,98.99
Knee Replacement Pre-Op Q Limping,NaN,137821,1415,98.97
Knee Replacement Pre-Op Q Standing,NaN,137783,1453,98.95
Knee Replacement Pre-Op Q Walking,NaN,137793,1443,98.95
Pre-Op Q Assisted,NaN,137725,1511,98.90
Post-Op Q Assisted,NaN,137641,1595,98.84
Post-Op Q Sucess,NaN,137470,1766,98.72
Post-Op Q Further Surgery,NaN,137465,1771,98.71
Post-Op Q Readmitted,NaN,137400,1836,98.66
Post-Op Q Satisfaction,NaN,137199,2037,98.52
Pre-Op Q Living Arrangements,NaN,137149,2087,98.48
Post-Op Q Self-Care,NaN,136508,2728,98.00
Post-Op Q Living Arrangements,NaN,136291,2945,97.84
Post-Op Q Mobility,NaN,136283,2953,97.83
Knee Replacement Post-Op Q Score,NaN,136276,2960,97.83
Post-Op Q Activity,NaN,136190,3046,97.76
Post-Op Q Anxiety,NaN,136052,3184,97.66
Post-Op Q Discomfort,NaN,135303,3933,97.09
Pre-Op Q Mobility,NaN,134950,4286,96.82
Pre-Op Q Self-Care,NaN,134826,4410,96.73
Pre-Op Q Activity,NaN,134747,4489,96.67
Pre-Op Q Anxiety,NaN,134075,5161,96.15
Post-Op Q Disability,NaN,134004,5232,96.10
Knee Replacement OKS Post-Op Q Predicted,float64,133855,5381,95.98
Knee Replacement Pre-Op Q Score,NaN,133719,5517,95.87
Pre-Op Q Discomfort,NaN,133696,5540,95.86
Pre-Op Q Disability,NaN,133329,5907,95.57
Post-Op Q EQ5D Index,float64,132962,6274,95.28
Pre-Op Q EQ5D Index,float64,131736,7500,94.31
Age Band,NaN,129834,9402,92.76
Gender,NaN,129834,9402,92.76
Post-Op Q Allergy,NaN,126457,12779,89.89
Knee Replacement EQ 5D Index Post-Op Q Predicted,float64,124914,14322,88.53
Post-Op Q Wound,NaN,124496,14740,88.16
Post-Op Q Urine,NaN,123702,15534,87.44
Post-Op Q Bleeding,NaN,122098,17138,85.96
Knee Replacement EQ VAS_Post-Op Q Predicted,float64,119813,19423,83.79
Post-Op Q Assisted By,NaN,10864,128372,-1081.63

In [95]:
display(df_Tbl_Knee_Replacement_Provider_cleaned)

df_Tbl_Knee_Replacement_Provider_cleaned["Pre-Op Q Assisted By"].unique()

,Provider Code,Procedure,Revision Flag,Year,Age Band,Gender,Pre-Op Q Assisted,Pre-Op Q Assisted By,Pre-Op Q Symptom Period,Pre-Op Q Previous Surgery,...,Knee Replacement Post-Op Q Walking,Knee Replacement Post-Op Q Standing,Knee Replacement Post-Op Q Limping,Knee Replacement Post-Op Q Kneeling,Knee Replacement Post-Op Q Work,Knee Replacement Post-Op Q Confidence,Knee Replacement Post-Op Q Shopping,Knee Replacement Post-Op Q Stairs,Knee Replacement Post-Op Q Score,Knee Replacement OKS Post-Op Q Predicted
0,ADP02,Knee Replacement,0,2016/17,<NA>,<NA>,2,0,4,2,...,2,2,3,2,3,1,3,2,29.0,28.123754
1,ADP02,Knee Replacement,0,2016/17,<NA>,<NA>,2,0,1,2,...,4,4,4,2,4,4,4,3,39.0,39.592750
2,ADP02,Knee Replacement,0,2016/17,<NA>,<NA>,2,0,2,2,...,4,4,4,3,4,4,4,4,45.0,40.250789
3,ADP02,Knee Replacement,0,2016/17,<NA>,<NA>,2,0,2,2,...,4,4,3,4,4,4,4,4,43.0,37.896225
4,ADP02,Knee Replacement,0,2016/17,<NA>,<NA>,1,0,3,2,...,3,4,2,2,2,4,2,3,36.0,40.142566
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139231,RYR,Knee Replacement,0,2018/19,80 to 89,2,2,0,2,2,...,2,3,3,1,3,4,2,4,33.0,36.247470
139232,RYR,Knee Replacement,0,2018/19,80 to 89,2,1,0,1,2,...,4,3,3,2,3,3,3,3,38.0,37.609414
139233,RYR,Knee Replacement,0,2018/19,80 to 89,2,2,0,2,2,...,3,3,3,0,3,3,4,4,34.0,35.843468
139234,RYR,Knee Replacement,0,2018/19,80 to 89,2,2,0,2,2,...,4,3,4,1,3,4,4,4,38.0,37.130713
139235,RYR,Knee Replacement,0,2018/19,80 to 89,2,2,0,2,2,...,3,2,3,2,2,3,4,2,29.0,38.101653

array([0])

In [100]:
col = "Pre-Op Q Assisted"

df_Tbl_Knee_Replacement_Provider_cleaned[col] = (
    pd.to_numeric(df_Tbl_Knee_Replacement_Provider_cleaned[col], errors="coerce")
      .replace({1: 1, 2: 0})
      .astype("Int64")   # keeps <NA> (pandas nullable int)
)

df_Tbl_Knee_Replacement_Provider_cleaned["Pre-Op Q Assisted"].unique()

col_1 = "Post-Op Q Assisted By"

assisted_map = {
    1: "Family member",
    2: "Other relative",
    3: "Carer",
    4: "Friend/Neighbour",
    5: "Healthcare professional",
    6: "Other",
    9: pd.NA
}

df_Tbl_Knee_Replacement_Provider_cleaned[col_1] = pd.to_numeric(df_Tbl_Knee_Replacement_Provider_cleaned[col_1], errors="coerce").map(assisted_map)

df_Tbl_Knee_Replacement_Provider_cleaned[col_1].unique()

array([nan, 'Other relative', 'Other', 'Family member',
       'Friend/Neighbour', 'Carer', 'Healthcare professional'],
      dtype=object)

In [97]:
display(df_Tbl_Knee_Replacement_Provider_cleaned)

,Provider Code,Procedure,Revision Flag,Year,Age Band,Gender,Pre-Op Q Assisted,Pre-Op Q Assisted By,Pre-Op Q Symptom Period,Pre-Op Q Previous Surgery,...,Knee Replacement Post-Op Q Walking,Knee Replacement Post-Op Q Standing,Knee Replacement Post-Op Q Limping,Knee Replacement Post-Op Q Kneeling,Knee Replacement Post-Op Q Work,Knee Replacement Post-Op Q Confidence,Knee Replacement Post-Op Q Shopping,Knee Replacement Post-Op Q Stairs,Knee Replacement Post-Op Q Score,Knee Replacement OKS Post-Op Q Predicted
0,ADP02,Knee Replacement,0,2016/17,<NA>,<NA>,0,NaN,4,2,...,2,2,3,2,3,1,3,2,29.0,28.123754
1,ADP02,Knee Replacement,0,2016/17,<NA>,<NA>,0,NaN,1,2,...,4,4,4,2,4,4,4,3,39.0,39.592750
2,ADP02,Knee Replacement,0,2016/17,<NA>,<NA>,0,NaN,2,2,...,4,4,4,3,4,4,4,4,45.0,40.250789
3,ADP02,Knee Replacement,0,2016/17,<NA>,<NA>,0,NaN,2,2,...,4,4,3,4,4,4,4,4,43.0,37.896225
4,ADP02,Knee Replacement,0,2016/17,<NA>,<NA>,1,NaN,3,2,...,3,4,2,2,2,4,2,3,36.0,40.142566
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139231,RYR,Knee Replacement,0,2018/19,80 to 89,2,0,NaN,2,2,...,2,3,3,1,3,4,2,4,33.0,36.247470
139232,RYR,Knee Replacement,0,2018/19,80 to 89,2,1,NaN,1,2,...,4,3,3,2,3,3,3,3,38.0,37.609414
139233,RYR,Knee Replacement,0,2018/19,80 to 89,2,0,NaN,2,2,...,3,3,3,0,3,3,4,4,34.0,35.843468
139234,RYR,Knee Replacement,0,2018/19,80 to 89,2,0,NaN,2,2,...,4,3,4,1,3,4,4,4,38.0,37.130713
139235,RYR,Knee Replacement,0,2018/19,80 to 89,2,0,NaN,2,2,...,3,2,3,2,2,3,4,2,29.0,38.101653

In [98]:
df_Tbl_Knee_Replacement_Provider_cleaned[col_1].unique()

array([nan], dtype=object)